#ifndef PIN_DEFS_H
#define PIN_DEFS_H

#define LED_R_PIN 10
#define LED_G_PIN 11
#define LED_B_PIN 12

#define SCREEN_SPI_SDA_PIN 33
#define SCREEN_SPI_SCL_PIN 21
#define SCREEN_SPI_CS_PIN 6
#define SCREEN_SPI_DC_PIN 5
#define SCREEN_SPI_RESET_PIN 4
#define SCREEN_SPI_BLK_PIN 7

#define KEY_R0_PIN 18
#define KEY_R1_PIN 8
#define KEY_R2_PIN 19
#define KEY_R3_PIN 20

#define KEY_C0_PIN 3
#define KEY_C1_PIN 17  // IO46 CANNOT OUTPUT, THUS CANNOT BE SET TO PULLED_DOWN, RELEASE VERSION WILL CONTAIN EXTERNAL PULL-DOWN RESISTOR, SO ONLY DEVEL VERSION WILL USE THIS PIN
#define KEY_C2_PIN 9

#endif  // PIN_DEFS_H